---
- name: Install nginx
  hosts: py
  become: true
  tasks:
    - name: Update Apt and all packages
      apt:
        name: "*"
        state:latest
        update_cache: yes


    - name: Installs nginx web server
      apt: pkg=nginx state=installed
      notify:
         - start nginx
  handlers:
    - name: start nginx
      service: name=nginx state=started	
