---
- name: Install nginx
  hosts: py
  become: true
  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
      
