---
- name: Install Elasticsearch, update, reboot, install kibana
  hosts: 10.0.0.85
  become: true
  roles:
    - { role: elasticsearch, es_instance_name: "node1" }
  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
    - name: Reboot the server for kernel update
      shell: ( sleep 3 && /sbin/reboot & )
      async: 0
      poll: 0 

    - name: Wait for the server to reboot
      local_action: wait_for host="{{ansible_host}}" delay=15 state=started port="{{ansible_port}}" connect_timeout=10 timeout=180
# Installing Kibana

# Install Kibana 
    - name: Install Kibana with apt
      apt:
       name: kibana 
# Configurations

    - name: Updating the config file to allow outside access
      lineinfile:
       destfile: /etc/kibana/kibana.yml
       regexp: 'server.host:'
       line: 'server.host: 0.0.0.0'

    - name: Defining server port
      lineinfile:
       destfile: /etc/kibana/kibana.yml
       regexp: 'server.port:'
       line: 'server.port: 5601'
    
    - name: Defining Elasticsearch URL
      lineinfile:
       destfile: /etc/kibana/kibana.yml
       regexp: 'elasticsearch.url:'
       line: 'elasticsearch.url: "http://localhost:9200"'
   
# Starting Kibana

    - name: Starting Kibana
      service:
       name: kibana
       state: started
