---
- name: Install nginx
  hosts: py
  become: true
  roles:
    - { role: elasticsearch, es_instance_name: "node1" }
  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
    - name: Task3 waiting for server to come back after
      local_action: wait_for host={{ ansible_ssh_host }} state=started


# Installing Kibana

# Install Kibana 
    - name: Install Kibana with apt
      apt:
       name: kibana 
# Configurations

    - name: Updating the config file to allow outside access
      lineinfile:
       destfile: /etc/kibana/kibana.yml
       regexp: 'server.host:'
       line: 'server.host: 0.0.0.0'

    - name: Defining server port
      lineinfile:
       destfile: /etc/kibana/kibana.yml
       regexp: 'server.port:'
       line: 'server.port: 5601'
    
    - name: Defining Elasticsearch URL
      lineinfile:
       destfile: /etc/kibana/kibana.yml
       regexp: 'elasticsearch.url:'
       line: 'elasticsearch.url: "http://localhost:9200"'
   
# Starting Kibana

    - name: Starting Kibana
      service:
       name: kibana
       state: started
