---
- name: Install nginx
  hosts: py
  become: true
  roles:
    - { role: elasticsearch, es_instance_name: "node1" }
  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
